title: 저장하고 까먹자
subtitle: ''
description: ''
keywords: null
author: Junggu Ji
language: ko
timezone: Asia/Seoul
url: 'https://jungguji.github.io'
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: YYYY-MM-DD
time_format: 'HH:mm:ss'
updated_option: date
per_page: 10
pagination_dir: page
include: null
exclude: null
ignore: null
plugins: '-hexo-math'
theme: tranquilpeak
deploy:
  type: git
  repo: 'https://github.com/jungguji/junggu.github.io.git'
  branch: master
mathjax:
  enable: true
sitemap:
  path: sitemap.xml
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub: null
nofollow:
  enable: true
  exclude:
    - exclude_1.com
    - exclude_2.com
robotstxt:
  useragent: '*'
  allow:
    - /
  sitemap: 'https://jungguji.github.io/sitemap.xml'
